Repository PPS-22-Scooby/PPS-22-Scooby, pull requests merged in 2024-07, with the labels that each got.

#26 fix: remove scalafix from the project configuraiton
  .github/workflows/test-code.yml
  .scalafix.conf
  build.sbt
  project/plugins.sbt
Labels: bug

#24 feat: PPS-45 exporter
  build.sbt
  src/main/scala/core/exporter/Exporter.scala
  src/test/resources/features/Exporter.back
  src/test/scala/core/exporter/ExporterTest.scala
  src/test/scala/exporter/DummyExporter.scala
  src/test/scala/exporter/StepDefinitions.scala
Labels: enhancement

#30 feat: scooby class
  src/main/scala/core/crawler/Crawler.scala
  src/main/scala/core/exporter/Exporter.scala
  src/main/scala/core/scooby/Configuration.scala
  src/main/scala/core/scooby/Scooby.scala
  src/main/scala/core/scraper/DataResult.scala
  src/main/scala/core/scraper/Scraper.scala
  src/main/scala/core/scraper/ScraperActor.scala
  src/main/scala/main.scala
  src/main/scala/utility/document/Explorer.scala
  src/main/scala/utility/document/html/HTML.scala
  src/main/scala/utility/http/URL.scala
  src/main/scala/utility/message/CommonMessages.scala
  src/test/resources/features/Result.feature
  src/test/resources/features/ScraperFiltering.feature
  src/test/scala/core/crawler/CrawlerLifecyleTest.scala
  src/test/scala/core/crawler/CrawlerTest.scala
  src/test/scala/core/crawler/StepDefinitions.scala
  src/test/scala/core/scraper/ScraperActorTest.scala
  src/test/scala/core/scraper/ScraperTest.scala
  src/test/scala/core/scraper/StepDefinitions.scala
  src/test/scala/core/scraper/result/StepDefinitions.scala
  src/test/scala/utility/document/ExplorerTest.scala
Labels: enhancement

#38 feat: handle http client creation
  src/main/scala/core/crawler/Crawler.scala
Labels: enhancement

#43 PPS-71 DSL - Scraping keywords
  src/main/scala/Application.scala
  src/main/scala/core/scraper/Scraper.scala
  src/main/scala/dsl/DSL.scala
  src/main/scala/dsl/Scrape.scala
  src/main/scala/utility/document/Explorer.scala
  src/main/scala/utility/document/html/HTML.scala
  src/test/scala/core/scraper/ScraperTest.scala
  src/test/scala/utility/document/ExplorerTest.scala
Labels: enhancement

#56 test: PPS-88 Implemented Scooby testing facilities
  src/main/scala/dsl/Entrypoint.scala
  src/test/resources/html/index.html
  src/test/resources/html/level1.0.html
  src/test/resources/html/level1.1.html
  src/test/resources/html/level2.0.html
  src/test/resources/html/level2.1.html
  src/test/scala/core/crawler/CrawlerTest.scala
  src/test/scala/dsl/DSLExporterTest.scala
  src/test/scala/dsl/ExampleTest.scala
  src/test/scala/dsl/util/ScoobyTest.scala
  src/test/scala/utility/MockServer.scala
Labels: enhancement

#57 Testing, refactoring and documentation for Config part of DSL
  src/main/scala/Application.scala
  src/main/scala/dsl/Config.scala
  src/test/scala/dsl/ConfigTest.scala
  src/test/scala/dsl/syntax/InvalidScopeTest.scala
Labels: documentation, enhancement

#60 test: Implement scrape tests
  src/main/scala/utility/document/html/HTML.scala
  src/test/scala/dsl/DSLScraperTest.scala
  src/test/scala/dsl/util/ScoobyTest.scala
  src/test/scala/utility/MockServer.scala
Labels: testing

#61 refactor: PPS-82 PPS-84 major refactoring for crawl and exporter tests
  src/main/scala/Application.scala
  src/main/scala/core/coordinator/Coordinator.scala
  src/main/scala/core/exporter/Exporter.scala
  src/main/scala/core/scooby/Configuration.scala
  src/main/scala/core/scooby/Scooby.scala
  src/main/scala/core/scraper/Aggregator.scala
  src/main/scala/dsl/Export.scala
  src/main/scala/utility/document/Explorer.scala
  src/main/scala/utility/document/html/HTML.scala
  src/main/scala/utility/http/backends/SttpSyncBackend.scala
  src/main/scala/utility/rule/Rule.scala
  src/test/resources/html/resources.html
  src/test/scala/core/crawler/CrawlerLifecyleTest.scala
  src/test/scala/dsl/DSLExporterTest.scala
  src/test/scala/dsl/DSLTest.scala
  src/test/scala/dsl/ExampleTest.scala
  src/test/scala/dsl/syntax/InvalidScopeTest.scala
  src/test/scala/dsl/util/ScoobyTest.scala
  src/test/scala/utility/MockServer.scala
Labels: enhancement

#68 refactor: PPS-81 remove rule
  src/main/scala/core/coordinator/Coordinator.scala
  src/main/scala/utility/rule/Rule.scala
  src/test/scala/utility/rule/Document.scala
  src/test/scala/utility/rule/RuleTest.scala
Labels: removal

#69 Fixed DSL support of JSON exporting
  src/main/scala/Application.scala
  src/main/scala/core/exporter/Exporter.scala
  src/main/scala/dsl/DSL.scala
  src/main/scala/dsl/Entrypoint.scala
  src/main/scala/dsl/Export.scala
  src/main/scala/utility/document/html/HTML.scala
  src/test/scala/dsl/DSLExporterTest.scala
  src/test/scala/dsl/ExampleTest.scala
Labels: bug, enhancement

#75 Documentation update and Entrypoint refactor
  src/main/scala/core/coordinator/Coordinator.scala
  src/main/scala/core/coordinator/Robots.scala
  src/main/scala/core/exporter/Exporter.scala
  src/main/scala/core/scooby/Configuration.scala
  src/main/scala/core/scooby/Scooby.scala
  src/main/scala/dsl/Config.scala
  src/main/scala/dsl/Crawl.scala
  src/main/scala/dsl/DSL.scala
  src/main/scala/dsl/Entrypoint.scala
  src/main/scala/dsl/Export.scala
  src/main/scala/dsl/Scrape.scala
  src/test/scala/dsl/util/ScoobyTest.scala
Labels: documentation, removal

#76 test: PPS-107 provided test for scraper single usage
  src/test/scala/core/scraper/ScraperTest.scala
Labels: testing

#74 PPS-97 PPS-106 test for the whole application, fixed errors causing different result on consequential run with same configurations
  src/main/scala/core/crawler/Crawler.scala
  src/main/scala/core/exporter/Exporter.scala
  src/main/scala/core/scraper/Scraper.scala
  src/test/scala/dsl/DSLTest.scala
Labels: testing

#78 Removed warning across files
  src/main/scala/core/coordinator/Coordinator.scala
  src/main/scala/core/scooby/Configuration.scala
  src/main/scala/core/scooby/Scooby.scala
  src/main/scala/utility/http/backends/SttpSyncBackend.scala
Labels: removal

#79 Release 1.0.0
  .github/workflows/publish-create-release.yml
  build.sbt
  project/plugins.sbt
  src/main/resources/logback.xml
  src/main/scala/Application.scala
  src/main/scala/core/coordinator/Coordinator.scala
  src/main/scala/core/coordinator/Robots.scala
  src/main/scala/core/crawler/Crawler.scala
  src/main/scala/core/exporter/Exporter.scala
  src/main/scala/core/scooby/Configuration.scala
  src/main/scala/core/scooby/Scooby.scala
  src/main/scala/core/scraper/Scraper.scala
  src/main/scala/dsl/Config.scala
  src/main/scala/dsl/Crawl.scala
  src/main/scala/dsl/DSL.scala
  src/main/scala/dsl/Entrypoint.scala
  src/main/scala/dsl/Export.scala
  src/main/scala/dsl/Scrape.scala
  src/main/scala/utility/document/html/HTML.scala
  src/main/scala/utility/http/URL.scala
  src/main/scala/utility/http/backends/SttpSyncBackend.scala
  src/main/scala/utility/rule/Rule.scala
  src/test/resources/features/CrawlerExplorationStrategy.back
  src/test/scala/core/crawler/CrawlerTest.scala
  src/test/scala/core/crawler/StepDefinitions.scala
  src/test/scala/core/exporter/ExporterRouterTest.scala
  src/test/scala/core/exporter/ExporterTest.scala
  src/test/scala/core/scraper/ScraperTest.scala
  src/test/scala/core/scraper/result/StepDefinitions.scala
  src/test/scala/dsl/DSLExporterTest.scala
  src/test/scala/dsl/DSLTest.scala
  src/test/scala/dsl/ExampleTest.scala
  src/test/scala/dsl/util/ScoobyTest.scala
  src/test/scala/utility/MockServer.scala
  src/test/scala/utility/document/ExplorerTest.scala
  src/test/scala/utility/http/RelativeUrlsTest.scala
  src/test/scala/utility/rule/Document.scala
  src/test/scala/utility/rule/RuleTest.scala
Labels: release

#81 fix: PPS-113 fix max number of links check
  src/main/scala/core/coordinator/Coordinator.scala
  src/test/scala/core/coordinator/CoordinatorTest.scala
Labels: bug
